weights: ./models/best.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: /tangyao/data/our_data/train/oks_data/data.npy
  label_path: /tangyao/data/our_data/train/oks_data/label.pkl
# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64
