work_dir: ./work_dir/shanghaitech_unet
# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 4 
  data_path: /tangyao/data/shanghaitech_process/train/data_train/xy/data.npy
  label_path: /tangyao/data/shanghaitech_process/train/data_train/xy/label.pkl
test_feeder_args:
  data_path: /tangyao/data/shanghaitech_process/train/data_train/xy/data.npy
  label_path: /tangyao/data/shanghaitech_process/train/data_train/xy/label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: 0
batch_size: 64
test_batch_size: 64

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 100



